//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.18 at 04:13:40 PM EET 
//


package com.nacid.web.config.xml;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nacid.web.config.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nacid.web.config.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Webconfig }
     * 
     */
    public Webconfig createWebconfig() {
        return new Webconfig();
    }

    /**
     * Create an instance of {@link Request2Handler }
     * 
     */
    public Request2Handler createRequest2Handler() {
        return new Request2Handler();
    }

    /**
     * Create an instance of {@link Screen }
     * 
     */
    public Screen createScreen() {
        return new Screen();
    }

    /**
     * Create an instance of {@link Mapping }
     * 
     */
    public Mapping createMapping() {
        return new Mapping();
    }

    /**
     * Create an instance of {@link Screen2Jsp }
     * 
     */
    public Screen2Jsp createScreen2Jsp() {
        return new Screen2Jsp();
    }

    /**
     * Create an instance of {@link Handler2Group }
     * 
     */
    public Handler2Group createHandler2Group() {
        return new Handler2Group();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

}
