//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-34 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.18 at 04:13:40 PM EET 
//


package com.nacid.web.config.xml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}handler2group"/>
 *         &lt;element ref="{}request2handler"/>
 *         &lt;element ref="{}screen2jsp"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "handler2Group",
    "request2Handler",
    "screen2Jsp"
})
@XmlRootElement(name = "webconfig")
public class Webconfig {

    @XmlElement(name = "handler2group", required = true)
    protected Handler2Group handler2Group;
    @XmlElement(name = "request2handler", required = true)
    protected Request2Handler request2Handler;
    @XmlElement(name = "screen2jsp", required = true)
    protected Screen2Jsp screen2Jsp;

    /**
     * Gets the value of the handler2Group property.
     * 
     * @return
     *     possible object is
     *     {@link Handler2Group }
     *     
     */
    public Handler2Group getHandler2Group() {
        return handler2Group;
    }

    /**
     * Sets the value of the handler2Group property.
     * 
     * @param value
     *     allowed object is
     *     {@link Handler2Group }
     *     
     */
    public void setHandler2Group(Handler2Group value) {
        this.handler2Group = value;
    }

    /**
     * Gets the value of the request2Handler property.
     * 
     * @return
     *     possible object is
     *     {@link Request2Handler }
     *     
     */
    public Request2Handler getRequest2Handler() {
        return request2Handler;
    }

    /**
     * Sets the value of the request2Handler property.
     * 
     * @param value
     *     allowed object is
     *     {@link Request2Handler }
     *     
     */
    public void setRequest2Handler(Request2Handler value) {
        this.request2Handler = value;
    }

    /**
     * Gets the value of the screen2Jsp property.
     * 
     * @return
     *     possible object is
     *     {@link Screen2Jsp }
     *     
     */
    public Screen2Jsp getScreen2Jsp() {
        return screen2Jsp;
    }

    /**
     * Sets the value of the screen2Jsp property.
     * 
     * @param value
     *     allowed object is
     *     {@link Screen2Jsp }
     *     
     */
    public void setScreen2Jsp(Screen2Jsp value) {
        this.screen2Jsp = value;
    }

}
